### ISSUE TITLE
Basculer la notion de fixe / volant au niveau du Membership

### ISSUE THREAD

**Issue by raphodn** [elefan-grenoble/gestion-compte#997]
### Quoi ?

Actuellement la notion de fixe / volant est défini au niveau du Bénéficiaire (champ `Beneficiary.flying`), sachant que : 
- être fixe est avant tout défini par l'inscription ou non du bénéficiaire à un créneau fixe
- un membre peut avoir 1 ou plusieurs bénéficiaires (paramètre `maximum_nb_of_beneficiaries_in_membership`)

A l'Elefan on souhaite basculer cette notion sur le Membership (`Membership.flying`), pour simplifier (?) la gestion et le suivi des membres

### Comment ?

- cela ne concerne que les coop qui ont `use_fly_and_fixed`
- la valeur par défaut sera `flying = 0 = false` (comme c'est le cas actuellement)
- migration pour basculer les données du Beneficiary vers le Membership (et prendre en compte les Membership avec plusieurs Beneficiary, en regardant le statut de leur mainBeneficiary)
- garder aussi le champ existant sur le Beneficiary pour donner le choix aux coop ?

### TODO

- [x] nouveau champ `Membership.flying`
- [x] migration à partir de données de `Beneficiary.flying`
- [x] nouveau paramètre `use_fly_and_fixed_entity` (valeurs possibles : `Membership`, `Beneficiary`)
- [x] membre coté admin : pouvoir toggle entre volant et fixe
- [ ] modifier le formulaire d'inscription (le champ "Equipe volante" y apparaît actuellement)
- [ ] modifier le formulaire de recherche de membres
- [ ] modifier l'affichage à plusieurs endroits (badges, warning si membre fixe sans créneau fixe, ou membre volant avec créneau fixe)
- [ ] nouvelle page avec la liste des membres fixes sans créneau fixes
